[package]
name = "helpers"
version = "0.1.0"
authors = ["Zahar <dev@zahar.pro>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
plotters = "0.3.0"
